server:
  port: 5555

spring:
  application:
    name: zuul-demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    eureka-client:
      serviceId: eureka-client
      path: /eureka/**
      stripPrefix: true
    ribbon-demo:
      path: /ribbon/**
      url: http://localhost:8181/
