server:
  port: 8080

spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9966
  sleuth:
    enabled: true
    sampler:
      percentage: 1

# 如果服务在指定的 失效时间 内仍没有发起心跳请求，将会被从EurekaServer剔除
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10     # 心跳间隔（秒），默认30s
    leaseExpirationDurationInSeconds: 30  # 失效时间，默认90s
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# Enable admin endpoints
endpoints:
  metrics:
    enabled: true
    sensitive: false
  dump:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  trace:
    enabled: true
    sensitive: false
  heapdump:
    enabled: true
    sensitive: false

demo:
  env: dev-0
