# Enable admin endpoints
endpoints:
  metrics:
    enabled: true
    sensitive: false
  dump:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  trace:
    enabled: true
    sensitive: false
  heapdump:
    enabled: true
    sensitive: false

# Enable hystrix support for feign
feign:
  hystrix:
    enabled: true

# Zipkin
spring:
  zipkin:
    base-url: http://localhost:9966
  sleuth:
    enabled: true
    sampler:
      percentage: 1
