eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  appConfig: feign-demo,ribbon-demo
  clusterNameExpression: new String("default")
  aggregator:
    clusterConfig: default
